spring:
  profiles:
      active: prod
  application:
    name: springmvc-shiro
    description: ${application.name} is a Spring Boot application
  resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/
  #thymeleaf
  thymeleaf:
    cache: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  #velocity

  #SOLR

  # JACKSON
  # DATA REST
  # MONGODB
  # REDIS
  # ELASTICSEARCH
  # DATABASE
  # DATASOURCE
  # ACTIVEMQ
  # RABBIT
  #eg....








