spring:
  application:
    name: springmvc-shiro
    description: ${application.name} is a Spring Boot application
  resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/

  address: 127.0.0.1
  port: 8080

logging:
  level:
      org.springframework.web: DEBUG
  file:  log/springmvc-shiro.log

jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/user_db?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
  username: root
  password: root

mybatis:
  typeAliasesPackage: com.bean
  mapperLocations: classpath:mapper/*






